### ISSUE TITLE
Possible to avoid WebGL?

### ISSUE THREAD

**Issue by firefoxlover** [versatiles-org/versatiles-frontend#14]
Using WebGL is a method of tracking, as websites get fingerprintable informations about your GPU.

This will not be an issue of the sites using this tool, but it is a preset of Tor-Browser, Librewolf, Arkenfox and other hardened Browsers. 

So websites using your Tiles will display a WebGL warning (NoScript) or not display at all when the Browser blocks WebGL itself (Tor I guess, Arkenfox)

What do you think, could this be possible, with a performance loss but better compatible?

Awesome project!

**Comment by MichaelKreil** [comment]
There are some [vector tiles plugins for Leaflet](https://leafletjs.com/plugins.html#vector-tiles) like [Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid) or [Leaflet.VectorTileLayer](https://gitlab.com/jkuebart/Leaflet.VectorTileLayer/). These plugins render vector tiles directly onto 2D canvases, eliminating the need for WebGL.

You could also prerender all tiles by using [Mapnik](https://mapnik.org) and this [Shortbread Mapnik style](https://shortbread.geofabrik.de/styles/).

But I think in the case of hardened browsers, not only WebGL is a problem, but JavaScript as well. So the only real alternative would be to "abandon interactivity" and simply use a screenshot of a map.

Of course, it would be great if a versatile server could generate a screenshot defined by url parameters. But that would be a more complex feature for the future.

**Comment by firefoxlover** [comment]
thanks for the response! 

I will just take Torbrowser default as standard. Yes a static image would of course also work, but having it run with only Javascript will be also fine. 

Thanks for your toolkit! Just replacing the frontend will be enough
