### ISSUE TITLE
Show bbox and min/max zoom level in preview

### ISSUE THREAD

**Issue by MichaelKreil** [versatiles-org/versatiles-frontend#16]
Otherwise it is hard to find the tiles of e.g. an extract

**Comment by hinricht** [comment]
Is this issue tracking the problem that starting versatiles with i.e. german tiles will result in this initial starting point, which makes it hard to zoom in the actual maps ?

![image](https://github.com/versatiles-org/versatiles-frontend/assets/120004353/90495d7b-6919-4c68-a018-f96d2a63cc8b)
