### ISSUE TITLE
Support PNG tiles

### ISSUE THREAD

**Issue by MichaelKreil** [versatiles-org/versatiles-frontend#19]

**Comment by hinricht** [comment]
I wanted to test this with latest frontend build from head of https://github.com/versatiles-org/versatiles-frontend.
I pull latest commit, ran `npm run dist`, resulting in a new `dist/frontend.br.tar`.
Using

    versatiles server -s dist/frontend.br.tar 'https://storage.googleapis.com/versatiles/download/planet/europe/germany/berlin-20230226.versatiles'

Results in a 

```
$ curl -i http://localhost:8080
HTTP/1.1 404 Not Found
content-length: 9
date: Mon, 02 Oct 2023 10:29:13 GMT

Not Found
```

Running the same command using the `frontend.br.tar` from the last release does work though,
so it seems there's a little regression ?

**Comment by hinricht** [comment]
Btw, I am using HEAD since there's no release yet.

**Comment by MichaelKreil** [comment]
Sorry. I marked the issue as closed, since the new feature is committed, but release will take some hours because i need to fix some other issues.
